language: java
install: true


dist: trusty
jdk:
  - oraclejdk8

env:
 global:
 - JAVA8_HOME

branches:
  only:
  - master
  - v7.6
    

script:
  - ./gradlew --continue clean build --scan -s -p modules/